# Generated by Django 2.2.1 on 2019-08-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20190824_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Accessrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.User')),
            ],
        ),
    ]
