# Generated by Django 2.2.1 on 2019-08-24 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20190824_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 15, 10, 35, 79362)),
        ),
    ]
